# Generated by Django 6.0 on 2026-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
