# Generated by Django 6.0 on 2026-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('engine', 'Engine'), ('tyre', 'Tyre'), ('brake', 'Brake'), ('accessory', 'Accessory')], default='accessory', max_length=50),
        ),
    ]
