# Generated by Django 6.0 on 2026-03-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0005_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
