# Generated by Django 6.0 on 2026-03-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('condition', models.CharField(default='Used', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
