# Generated by Django 6.0 on 2026-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
