# Generated by Django 6.0 on 2026-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpp', '0005_product_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
